<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sasmodel" nsURI="http://www.example.org/sasmodel" nsPrefix="sasmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Subsystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gauge" upperBound="-1"
        eType="#//Gauge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measuredoutput" upperBound="-1"
        eType="#//MeasuredOutput" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Managing" eSuperTypes="#//Subsystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlloopmanager" lowerBound="1"
        eType="#//ControlLoopManager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Managed" eSuperTypes="#//Subsystem"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlLoopManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlloop" lowerBound="1"
        upperBound="-1" eType="#//ControlLoop"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synchronized" eSuperTypes="#//ControlLoopManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="Coordinated" eSuperTypes="#//ControlLoopManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="Independent" eSuperTypes="#//ControlLoopManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControlLoop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitor" lowerBound="1"
        upperBound="-1" eType="#//Monitor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzer" lowerBound="1"
        upperBound="-1" eType="#//Analyzer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="planner" upperBound="-1"
        eType="#//Planner" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executor" lowerBound="1"
        upperBound="-1" eType="#//Executor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Monitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" upperBound="-1"
        eType="#//Sensor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Analyzer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledge" lowerBound="1"
        eType="#//Knowledge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Planner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledge" lowerBound="1"
        eType="#//Knowledge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Executor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="effector" upperBound="-1"
        eType="#//Effector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Knowledge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceinput" lowerBound="1"
        upperBound="-1" eType="#//ReferenceInput" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceInput"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gauge" eType="#//Gauge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Effector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="measuredoutput" eType="#//MeasuredOutput"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeasuredOutput"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gauge"/>
</ecore:EPackage>
