/**
 * generated by Xtext 2.10.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DCL Effector</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDCLEffector()
 * @model
 * @generated
 */
public interface DCLEffector extends DCLAbstractions
{
} // DCLEffector
