/**
 * generated by Xtext 2.10.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSL Analyzer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DSLAnalyzer#getAnlyzerinterfaces <em>Anlyzerinterfaces</em>}</li>
 * </ul>
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDSLAnalyzer()
 * @model
 * @generated
 */
public interface DSLAnalyzer extends DSLAbstraction
{
  /**
   * Returns the value of the '<em><b>Anlyzerinterfaces</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.sas.xtext.sasdsl.sasDsl.AnalyzerInterface}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Anlyzerinterfaces</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Anlyzerinterfaces</em>' containment reference list.
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDSLAnalyzer_Anlyzerinterfaces()
   * @model containment="true"
   * @generated
   */
  EList<AnalyzerInterface> getAnlyzerinterfaces();

} // DSLAnalyzer
