/**
 * generated by Xtext 2.10.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSL Control Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDSLControlLoop()
 * @model
 * @generated
 */
public interface DSLControlLoop extends DSLAbstraction
{
} // DSLControlLoop
