/**
 * generated by Xtext 2.10.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSL Control Loop Manager</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DSLControlLoopManager#getManaging <em>Managing</em>}</li>
 * </ul>
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDSLControlLoopManager()
 * @model
 * @generated
 */
public interface DSLControlLoopManager extends DSLAbstractions, DSLContainrerForCL
{
  /**
   * Returns the value of the '<em><b>Managing</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Managing</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Managing</em>' reference.
   * @see #setManaging(DSLManaging)
   * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDSLControlLoopManager_Managing()
   * @model
   * @generated
   */
  DSLManaging getManaging();

  /**
   * Sets the value of the '{@link br.ufscar.sas.xtext.sasdsl.sasDsl.DSLControlLoopManager#getManaging <em>Managing</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Managing</em>' reference.
   * @see #getManaging()
   * @generated
   */
  void setManaging(DSLManaging value);

} // DSLControlLoopManager
