/**
 * generated by Xtext 2.10.0
 */
package br.ufscar.sas.xtext.sasdsl.sasDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DSL Effector</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufscar.sas.xtext.sasdsl.sasDsl.SasDslPackage#getDSLEffector()
 * @model
 * @generated
 */
public interface DSLEffector extends DSLAbstraction
{
} // DSLEffector
