/*
 * generated by Xtext 2.10.0
 */
package br.ufscar.sas.xtext.sasdsl.ide.contentassist.antlr;

import br.ufscar.sas.xtext.sasdsl.ide.contentassist.antlr.internal.InternalSasDslParser;
import br.ufscar.sas.xtext.sasdsl.services.SasDslGrammarAccess;
import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class SasDslParser extends AbstractContentAssistParser {

	@Inject
	private SasDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalSasDslParser createParser() {
		InternalSasDslParser result = new InternalSasDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDSLRulesAccess().getAlternatives(), "rule__DSLRules__Alternatives");
					put(grammarAccess.getDSLRuleControllerAccess().getAlternatives(), "rule__DSLRuleController__Alternatives");
					put(grammarAccess.getDSLRuleMonitorAccess().getAlternatives(), "rule__DSLRuleMonitor__Alternatives");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getAlternatives(), "rule__DSLRuleAnalyzer__Alternatives");
					put(grammarAccess.getDSLRulePlannerAccess().getAlternatives(), "rule__DSLRulePlanner__Alternatives");
					put(grammarAccess.getDSLRuleExecutorAccess().getAlternatives(), "rule__DSLRuleExecutor__Alternatives");
					put(grammarAccess.getDSLRuleMOAccess().getAlternatives(), "rule__DSLRuleMO__Alternatives");
					put(grammarAccess.getDSLRuleRIAccess().getAlternatives(), "rule__DSLRuleRI__Alternatives");
					put(grammarAccess.getDSLTypeMCAccess().getAlternatives(), "rule__DSLTypeMC__Alternatives");
					put(grammarAccess.getArchitectureDefinitionAccess().getGroup(), "rule__ArchitectureDefinition__Group__0");
					put(grammarAccess.getDSLRulesAccess().getGroup_0(), "rule__DSLRules__Group_0__0");
					put(grammarAccess.getDSLRulesAccess().getGroup_1(), "rule__DSLRules__Group_1__0");
					put(grammarAccess.getDSLRulesAccess().getGroup_2(), "rule__DSLRules__Group_2__0");
					put(grammarAccess.getDSLRulesAccess().getGroup_3(), "rule__DSLRules__Group_3__0");
					put(grammarAccess.getDSLRulesAccess().getGroup_4(), "rule__DSLRules__Group_4__0");
					put(grammarAccess.getDSLRulesAccess().getGroup_5(), "rule__DSLRules__Group_5__0");
					put(grammarAccess.getDSLRulesAccess().getGroup_6(), "rule__DSLRules__Group_6__0");
					put(grammarAccess.getDSLRuleControllerAccess().getGroup_0(), "rule__DSLRuleController__Group_0__0");
					put(grammarAccess.getDSLRuleControllerAccess().getGroup_1(), "rule__DSLRuleController__Group_1__0");
					put(grammarAccess.getDSLRuleControllerAccess().getGroup_2(), "rule__DSLRuleController__Group_2__0");
					put(grammarAccess.getDSLRuleControllerAccess().getGroup_3(), "rule__DSLRuleController__Group_3__0");
					put(grammarAccess.getDSLRuleControllerAccess().getGroup_4(), "rule__DSLRuleController__Group_4__0");
					put(grammarAccess.getDSLRuleControllerAccess().getGroup_5(), "rule__DSLRuleController__Group_5__0");
					put(grammarAccess.getDSLRuleControllerAccess().getGroup_6(), "rule__DSLRuleController__Group_6__0");
					put(grammarAccess.getDSLRuleControllerAccess().getGroup_7(), "rule__DSLRuleController__Group_7__0");
					put(grammarAccess.getDSLRuleMonitorAccess().getGroup_0(), "rule__DSLRuleMonitor__Group_0__0");
					put(grammarAccess.getDSLRuleMonitorAccess().getGroup_1(), "rule__DSLRuleMonitor__Group_1__0");
					put(grammarAccess.getDSLRuleMonitorAccess().getGroup_2(), "rule__DSLRuleMonitor__Group_2__0");
					put(grammarAccess.getDSLRuleMonitorAccess().getGroup_3(), "rule__DSLRuleMonitor__Group_3__0");
					put(grammarAccess.getDSLRuleMonitorAccess().getGroup_4(), "rule__DSLRuleMonitor__Group_4__0");
					put(grammarAccess.getDSLRuleMonitorAccess().getGroup_5(), "rule__DSLRuleMonitor__Group_5__0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getGroup_0(), "rule__DSLRuleAnalyzer__Group_0__0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getGroup_1(), "rule__DSLRuleAnalyzer__Group_1__0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getGroup_2(), "rule__DSLRuleAnalyzer__Group_2__0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getGroup_3(), "rule__DSLRuleAnalyzer__Group_3__0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getGroup_4(), "rule__DSLRuleAnalyzer__Group_4__0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getGroup_5(), "rule__DSLRuleAnalyzer__Group_5__0");
					put(grammarAccess.getDSLRulePlannerAccess().getGroup_0(), "rule__DSLRulePlanner__Group_0__0");
					put(grammarAccess.getDSLRulePlannerAccess().getGroup_1(), "rule__DSLRulePlanner__Group_1__0");
					put(grammarAccess.getDSLRulePlannerAccess().getGroup_2(), "rule__DSLRulePlanner__Group_2__0");
					put(grammarAccess.getDSLRulePlannerAccess().getGroup_3(), "rule__DSLRulePlanner__Group_3__0");
					put(grammarAccess.getDSLRulePlannerAccess().getGroup_4(), "rule__DSLRulePlanner__Group_4__0");
					put(grammarAccess.getDSLRulePlannerAccess().getGroup_5(), "rule__DSLRulePlanner__Group_5__0");
					put(grammarAccess.getDSLRuleExecutorAccess().getGroup_0(), "rule__DSLRuleExecutor__Group_0__0");
					put(grammarAccess.getDSLRuleExecutorAccess().getGroup_1(), "rule__DSLRuleExecutor__Group_1__0");
					put(grammarAccess.getDSLRuleExecutorAccess().getGroup_2(), "rule__DSLRuleExecutor__Group_2__0");
					put(grammarAccess.getDSLRuleExecutorAccess().getGroup_3(), "rule__DSLRuleExecutor__Group_3__0");
					put(grammarAccess.getDSLRuleExecutorAccess().getGroup_4(), "rule__DSLRuleExecutor__Group_4__0");
					put(grammarAccess.getDSLRuleExecutorAccess().getGroup_5(), "rule__DSLRuleExecutor__Group_5__0");
					put(grammarAccess.getDSLRuleMOAccess().getGroup_0(), "rule__DSLRuleMO__Group_0__0");
					put(grammarAccess.getDSLRuleMOAccess().getGroup_1(), "rule__DSLRuleMO__Group_1__0");
					put(grammarAccess.getDSLRuleRIAccess().getGroup_0(), "rule__DSLRuleRI__Group_0__0");
					put(grammarAccess.getDSLRuleRIAccess().getGroup_1(), "rule__DSLRuleRI__Group_1__0");
					put(grammarAccess.getDSLManagingAccess().getGroup(), "rule__DSLManaging__Group__0");
					put(grammarAccess.getDSLManagedAccess().getGroup(), "rule__DSLManaged__Group__0");
					put(grammarAccess.getDSLManagerControllerAccess().getGroup(), "rule__DSLManagerController__Group__0");
					put(grammarAccess.getDSLControllerAccess().getGroup(), "rule__DSLController__Group__0");
					put(grammarAccess.getDSLControllerAccess().getGroup_2(), "rule__DSLController__Group_2__0");
					put(grammarAccess.getDSLControllerAccess().getGroup_2_2(), "rule__DSLController__Group_2_2__0");
					put(grammarAccess.getDSLMonitorAccess().getGroup(), "rule__DSLMonitor__Group__0");
					put(grammarAccess.getDSLMonitorAccess().getGroup_2(), "rule__DSLMonitor__Group_2__0");
					put(grammarAccess.getDSLMonitorAccess().getGroup_2_2(), "rule__DSLMonitor__Group_2_2__0");
					put(grammarAccess.getDSLAnalyzerAccess().getGroup(), "rule__DSLAnalyzer__Group__0");
					put(grammarAccess.getDSLAnalyzerAccess().getGroup_2(), "rule__DSLAnalyzer__Group_2__0");
					put(grammarAccess.getDSLAnalyzerAccess().getGroup_2_2(), "rule__DSLAnalyzer__Group_2_2__0");
					put(grammarAccess.getDSLPlannerAccess().getGroup(), "rule__DSLPlanner__Group__0");
					put(grammarAccess.getDSLPlannerAccess().getGroup_2(), "rule__DSLPlanner__Group_2__0");
					put(grammarAccess.getDSLPlannerAccess().getGroup_2_2(), "rule__DSLPlanner__Group_2_2__0");
					put(grammarAccess.getDSLExecutorAccess().getGroup(), "rule__DSLExecutor__Group__0");
					put(grammarAccess.getDSLExecutorAccess().getGroup_2(), "rule__DSLExecutor__Group_2__0");
					put(grammarAccess.getDSLExecutorAccess().getGroup_2_2(), "rule__DSLExecutor__Group_2_2__0");
					put(grammarAccess.getDSLKnowledgeAccess().getGroup(), "rule__DSLKnowledge__Group__0");
					put(grammarAccess.getDSLKnowledgeAccess().getGroup_2(), "rule__DSLKnowledge__Group_2__0");
					put(grammarAccess.getDSLKnowledgeAccess().getGroup_2_2(), "rule__DSLKnowledge__Group_2_2__0");
					put(grammarAccess.getDSLSensorAccess().getGroup(), "rule__DSLSensor__Group__0");
					put(grammarAccess.getDSLSensorAccess().getGroup_2(), "rule__DSLSensor__Group_2__0");
					put(grammarAccess.getDSLSensorAccess().getGroup_2_2(), "rule__DSLSensor__Group_2_2__0");
					put(grammarAccess.getDSLEffectorAccess().getGroup(), "rule__DSLEffector__Group__0");
					put(grammarAccess.getDSLEffectorAccess().getGroup_2(), "rule__DSLEffector__Group_2__0");
					put(grammarAccess.getDSLEffectorAccess().getGroup_2_2(), "rule__DSLEffector__Group_2_2__0");
					put(grammarAccess.getDSLReferenceInputAccess().getGroup(), "rule__DSLReferenceInput__Group__0");
					put(grammarAccess.getDSLMeasuredOutputAccess().getGroup(), "rule__DSLMeasuredOutput__Group__0");
					put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
					put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
					put(grammarAccess.getArchitectureDefinitionAccess().getNameAssignment_1(), "rule__ArchitectureDefinition__NameAssignment_1");
					put(grammarAccess.getArchitectureDefinitionAccess().getManagingAssignment_3(), "rule__ArchitectureDefinition__ManagingAssignment_3");
					put(grammarAccess.getArchitectureDefinitionAccess().getManagedAssignment_4(), "rule__ArchitectureDefinition__ManagedAssignment_4");
					put(grammarAccess.getArchitectureDefinitionAccess().getRulesAssignment_8(), "rule__ArchitectureDefinition__RulesAssignment_8");
					put(grammarAccess.getDSLRuleControllerAccess().getControllerAssignment_0_0(), "rule__DSLRuleController__ControllerAssignment_0_0");
					put(grammarAccess.getDSLRuleControllerAccess().getMonitorAssignment_0_2(), "rule__DSLRuleController__MonitorAssignment_0_2");
					put(grammarAccess.getDSLRuleControllerAccess().getControllerAssignment_1_0(), "rule__DSLRuleController__ControllerAssignment_1_0");
					put(grammarAccess.getDSLRuleControllerAccess().getMonitorAssignment_1_2(), "rule__DSLRuleController__MonitorAssignment_1_2");
					put(grammarAccess.getDSLRuleControllerAccess().getMonitorinterfaceAssignment_1_4(), "rule__DSLRuleController__MonitorinterfaceAssignment_1_4");
					put(grammarAccess.getDSLRuleControllerAccess().getControllerAssignment_2_0(), "rule__DSLRuleController__ControllerAssignment_2_0");
					put(grammarAccess.getDSLRuleControllerAccess().getAnalyzerAssignment_2_2(), "rule__DSLRuleController__AnalyzerAssignment_2_2");
					put(grammarAccess.getDSLRuleControllerAccess().getControllerAssignment_3_0(), "rule__DSLRuleController__ControllerAssignment_3_0");
					put(grammarAccess.getDSLRuleControllerAccess().getAnalyzerAssignment_3_2(), "rule__DSLRuleController__AnalyzerAssignment_3_2");
					put(grammarAccess.getDSLRuleControllerAccess().getAnalyzerinterfaceAssignment_3_4(), "rule__DSLRuleController__AnalyzerinterfaceAssignment_3_4");
					put(grammarAccess.getDSLRuleControllerAccess().getControllerAssignment_4_0(), "rule__DSLRuleController__ControllerAssignment_4_0");
					put(grammarAccess.getDSLRuleControllerAccess().getPlannerAssignment_4_2(), "rule__DSLRuleController__PlannerAssignment_4_2");
					put(grammarAccess.getDSLRuleControllerAccess().getControllerAssignment_5_0(), "rule__DSLRuleController__ControllerAssignment_5_0");
					put(grammarAccess.getDSLRuleControllerAccess().getPlannerAssignment_5_2(), "rule__DSLRuleController__PlannerAssignment_5_2");
					put(grammarAccess.getDSLRuleControllerAccess().getPlannerinterfaceAssignment_5_4(), "rule__DSLRuleController__PlannerinterfaceAssignment_5_4");
					put(grammarAccess.getDSLRuleControllerAccess().getControllerAssignment_6_0(), "rule__DSLRuleController__ControllerAssignment_6_0");
					put(grammarAccess.getDSLRuleControllerAccess().getExecutorAssignment_6_2(), "rule__DSLRuleController__ExecutorAssignment_6_2");
					put(grammarAccess.getDSLRuleControllerAccess().getControllerAssignment_7_0(), "rule__DSLRuleController__ControllerAssignment_7_0");
					put(grammarAccess.getDSLRuleControllerAccess().getExecutorAssignment_7_2(), "rule__DSLRuleController__ExecutorAssignment_7_2");
					put(grammarAccess.getDSLRuleControllerAccess().getExecutorinterfaceAssignment_7_4(), "rule__DSLRuleController__ExecutorinterfaceAssignment_7_4");
					put(grammarAccess.getDSLRuleMonitorAccess().getMonitorAssignment_0_0(), "rule__DSLRuleMonitor__MonitorAssignment_0_0");
					put(grammarAccess.getDSLRuleMonitorAccess().getSensorAssignment_0_2(), "rule__DSLRuleMonitor__SensorAssignment_0_2");
					put(grammarAccess.getDSLRuleMonitorAccess().getMonitorAssignment_1_0(), "rule__DSLRuleMonitor__MonitorAssignment_1_0");
					put(grammarAccess.getDSLRuleMonitorAccess().getSensorAssignment_1_2(), "rule__DSLRuleMonitor__SensorAssignment_1_2");
					put(grammarAccess.getDSLRuleMonitorAccess().getSensorinterfaceAssignment_1_4(), "rule__DSLRuleMonitor__SensorinterfaceAssignment_1_4");
					put(grammarAccess.getDSLRuleMonitorAccess().getMonitorAssignment_2_0(), "rule__DSLRuleMonitor__MonitorAssignment_2_0");
					put(grammarAccess.getDSLRuleMonitorAccess().getKnowledgeAssignment_2_2(), "rule__DSLRuleMonitor__KnowledgeAssignment_2_2");
					put(grammarAccess.getDSLRuleMonitorAccess().getMonitorAssignment_3_0(), "rule__DSLRuleMonitor__MonitorAssignment_3_0");
					put(grammarAccess.getDSLRuleMonitorAccess().getKnowledgeAssignment_3_2(), "rule__DSLRuleMonitor__KnowledgeAssignment_3_2");
					put(grammarAccess.getDSLRuleMonitorAccess().getKnowledgeinterfaceAssignment_3_4(), "rule__DSLRuleMonitor__KnowledgeinterfaceAssignment_3_4");
					put(grammarAccess.getDSLRuleMonitorAccess().getMonitorAssignment_4_0(), "rule__DSLRuleMonitor__MonitorAssignment_4_0");
					put(grammarAccess.getDSLRuleMonitorAccess().getAnalyzerAssignment_4_2(), "rule__DSLRuleMonitor__AnalyzerAssignment_4_2");
					put(grammarAccess.getDSLRuleMonitorAccess().getMonitorAssignment_5_0(), "rule__DSLRuleMonitor__MonitorAssignment_5_0");
					put(grammarAccess.getDSLRuleMonitorAccess().getAnalyzerAssignment_5_2(), "rule__DSLRuleMonitor__AnalyzerAssignment_5_2");
					put(grammarAccess.getDSLRuleMonitorAccess().getAnalyzerinterfaceAssignment_5_4(), "rule__DSLRuleMonitor__AnalyzerinterfaceAssignment_5_4");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getAnalyzerAssignment_0_0(), "rule__DSLRuleAnalyzer__AnalyzerAssignment_0_0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getKnowledgeAssignment_0_2(), "rule__DSLRuleAnalyzer__KnowledgeAssignment_0_2");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getAnalyzerAssignment_1_0(), "rule__DSLRuleAnalyzer__AnalyzerAssignment_1_0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getKnowledgeAssignment_1_2(), "rule__DSLRuleAnalyzer__KnowledgeAssignment_1_2");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getKnowledgeinterfaceAssignment_1_4(), "rule__DSLRuleAnalyzer__KnowledgeinterfaceAssignment_1_4");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getAnalyzerAssignment_2_0(), "rule__DSLRuleAnalyzer__AnalyzerAssignment_2_0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getMonitorAssignment_2_2(), "rule__DSLRuleAnalyzer__MonitorAssignment_2_2");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getAnalyzerAssignment_3_0(), "rule__DSLRuleAnalyzer__AnalyzerAssignment_3_0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getKnowledgeAssignment_3_2(), "rule__DSLRuleAnalyzer__KnowledgeAssignment_3_2");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getMonitorinterfaceAssignment_3_4(), "rule__DSLRuleAnalyzer__MonitorinterfaceAssignment_3_4");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getAnalyzerAssignment_4_0(), "rule__DSLRuleAnalyzer__AnalyzerAssignment_4_0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getPlannerAssignment_4_2(), "rule__DSLRuleAnalyzer__PlannerAssignment_4_2");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getAnalyzerAssignment_5_0(), "rule__DSLRuleAnalyzer__AnalyzerAssignment_5_0");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getPlannerAssignment_5_2(), "rule__DSLRuleAnalyzer__PlannerAssignment_5_2");
					put(grammarAccess.getDSLRuleAnalyzerAccess().getPlannerinterfaceAssignment_5_4(), "rule__DSLRuleAnalyzer__PlannerinterfaceAssignment_5_4");
					put(grammarAccess.getDSLRulePlannerAccess().getPlannerAssignment_0_0(), "rule__DSLRulePlanner__PlannerAssignment_0_0");
					put(grammarAccess.getDSLRulePlannerAccess().getKnowledgeAssignment_0_2(), "rule__DSLRulePlanner__KnowledgeAssignment_0_2");
					put(grammarAccess.getDSLRulePlannerAccess().getPlannerAssignment_1_0(), "rule__DSLRulePlanner__PlannerAssignment_1_0");
					put(grammarAccess.getDSLRulePlannerAccess().getKnowledgeAssignment_1_2(), "rule__DSLRulePlanner__KnowledgeAssignment_1_2");
					put(grammarAccess.getDSLRulePlannerAccess().getKnowledgeinterfaceAssignment_1_4(), "rule__DSLRulePlanner__KnowledgeinterfaceAssignment_1_4");
					put(grammarAccess.getDSLRulePlannerAccess().getPlannerAssignment_2_0(), "rule__DSLRulePlanner__PlannerAssignment_2_0");
					put(grammarAccess.getDSLRulePlannerAccess().getAnalyzerAssignment_2_2(), "rule__DSLRulePlanner__AnalyzerAssignment_2_2");
					put(grammarAccess.getDSLRulePlannerAccess().getPlannerAssignment_3_0(), "rule__DSLRulePlanner__PlannerAssignment_3_0");
					put(grammarAccess.getDSLRulePlannerAccess().getAnalyzerAssignment_3_2(), "rule__DSLRulePlanner__AnalyzerAssignment_3_2");
					put(grammarAccess.getDSLRulePlannerAccess().getAnalyzerinterfaceAssignment_3_4(), "rule__DSLRulePlanner__AnalyzerinterfaceAssignment_3_4");
					put(grammarAccess.getDSLRulePlannerAccess().getPlannerAssignment_4_0(), "rule__DSLRulePlanner__PlannerAssignment_4_0");
					put(grammarAccess.getDSLRulePlannerAccess().getExecutorAssignment_4_2(), "rule__DSLRulePlanner__ExecutorAssignment_4_2");
					put(grammarAccess.getDSLRulePlannerAccess().getPlannerAssignment_5_0(), "rule__DSLRulePlanner__PlannerAssignment_5_0");
					put(grammarAccess.getDSLRulePlannerAccess().getExecutorAssignment_5_2(), "rule__DSLRulePlanner__ExecutorAssignment_5_2");
					put(grammarAccess.getDSLRulePlannerAccess().getExecutorinterfaceAssignment_5_4(), "rule__DSLRulePlanner__ExecutorinterfaceAssignment_5_4");
					put(grammarAccess.getDSLRuleExecutorAccess().getExecutorAssignment_0_0(), "rule__DSLRuleExecutor__ExecutorAssignment_0_0");
					put(grammarAccess.getDSLRuleExecutorAccess().getEffectorAssignment_0_2(), "rule__DSLRuleExecutor__EffectorAssignment_0_2");
					put(grammarAccess.getDSLRuleExecutorAccess().getExecutorAssignment_1_0(), "rule__DSLRuleExecutor__ExecutorAssignment_1_0");
					put(grammarAccess.getDSLRuleExecutorAccess().getEffectorAssignment_1_2(), "rule__DSLRuleExecutor__EffectorAssignment_1_2");
					put(grammarAccess.getDSLRuleExecutorAccess().getEffectorinterfaceAssignment_1_4(), "rule__DSLRuleExecutor__EffectorinterfaceAssignment_1_4");
					put(grammarAccess.getDSLRuleExecutorAccess().getExecutorAssignment_2_0(), "rule__DSLRuleExecutor__ExecutorAssignment_2_0");
					put(grammarAccess.getDSLRuleExecutorAccess().getPlannerAssignment_2_2(), "rule__DSLRuleExecutor__PlannerAssignment_2_2");
					put(grammarAccess.getDSLRuleExecutorAccess().getExecutorAssignment_3_0(), "rule__DSLRuleExecutor__ExecutorAssignment_3_0");
					put(grammarAccess.getDSLRuleExecutorAccess().getPlannerAssignment_3_2(), "rule__DSLRuleExecutor__PlannerAssignment_3_2");
					put(grammarAccess.getDSLRuleExecutorAccess().getPlannerinterfaceAssignment_3_4(), "rule__DSLRuleExecutor__PlannerinterfaceAssignment_3_4");
					put(grammarAccess.getDSLRuleExecutorAccess().getExecutorAssignment_4_0(), "rule__DSLRuleExecutor__ExecutorAssignment_4_0");
					put(grammarAccess.getDSLRuleExecutorAccess().getKnowledgeAssignment_4_2(), "rule__DSLRuleExecutor__KnowledgeAssignment_4_2");
					put(grammarAccess.getDSLRuleExecutorAccess().getExecutorAssignment_5_0(), "rule__DSLRuleExecutor__ExecutorAssignment_5_0");
					put(grammarAccess.getDSLRuleExecutorAccess().getKnowledgeAssignment_5_2(), "rule__DSLRuleExecutor__KnowledgeAssignment_5_2");
					put(grammarAccess.getDSLRuleExecutorAccess().getKnowledgeinterfaceAssignment_5_4(), "rule__DSLRuleExecutor__KnowledgeinterfaceAssignment_5_4");
					put(grammarAccess.getDSLRuleMOAccess().getSensorAssignment_0_0(), "rule__DSLRuleMO__SensorAssignment_0_0");
					put(grammarAccess.getDSLRuleMOAccess().getMeasuredAssignment_0_2(), "rule__DSLRuleMO__MeasuredAssignment_0_2");
					put(grammarAccess.getDSLRuleMOAccess().getSensorAssignment_1_0(), "rule__DSLRuleMO__SensorAssignment_1_0");
					put(grammarAccess.getDSLRuleMOAccess().getMeasuredAssignment_1_2(), "rule__DSLRuleMO__MeasuredAssignment_1_2");
					put(grammarAccess.getDSLRuleRIAccess().getAnalyzerAssignment_0_0(), "rule__DSLRuleRI__AnalyzerAssignment_0_0");
					put(grammarAccess.getDSLRuleRIAccess().getReferenceAssignment_0_2(), "rule__DSLRuleRI__ReferenceAssignment_0_2");
					put(grammarAccess.getDSLRuleRIAccess().getAnalyzerAssignment_1_0(), "rule__DSLRuleRI__AnalyzerAssignment_1_0");
					put(grammarAccess.getDSLRuleRIAccess().getReferenceAssignment_1_2(), "rule__DSLRuleRI__ReferenceAssignment_1_2");
					put(grammarAccess.getDSLManagingAccess().getNameAssignment_1(), "rule__DSLManaging__NameAssignment_1");
					put(grammarAccess.getDSLManagingAccess().getManagerControllerAssignment_3(), "rule__DSLManaging__ManagerControllerAssignment_3");
					put(grammarAccess.getDSLManagingAccess().getControllerAssignment_4(), "rule__DSLManaging__ControllerAssignment_4");
					put(grammarAccess.getDSLManagedAccess().getNameAssignment_1(), "rule__DSLManaged__NameAssignment_1");
					put(grammarAccess.getDSLManagedAccess().getSensorAssignment_3(), "rule__DSLManaged__SensorAssignment_3");
					put(grammarAccess.getDSLManagedAccess().getEffectorAssignment_4(), "rule__DSLManaged__EffectorAssignment_4");
					put(grammarAccess.getDSLManagedAccess().getMeasuredOutputAssignment_5(), "rule__DSLManaged__MeasuredOutputAssignment_5");
					put(grammarAccess.getDSLManagerControllerAccess().getNameAssignment_1(), "rule__DSLManagerController__NameAssignment_1");
					put(grammarAccess.getDSLManagerControllerAccess().getControllerAssignment_5(), "rule__DSLManagerController__ControllerAssignment_5");
					put(grammarAccess.getDSLControllerAccess().getNameAssignment_1(), "rule__DSLController__NameAssignment_1");
					put(grammarAccess.getDSLControllerAccess().getControllerinterfacesAssignment_2_1(), "rule__DSLController__ControllerinterfacesAssignment_2_1");
					put(grammarAccess.getDSLControllerAccess().getControllerinterfacesAssignment_2_2_1(), "rule__DSLController__ControllerinterfacesAssignment_2_2_1");
					put(grammarAccess.getDSLControllerAccess().getMonitorAssignment_4(), "rule__DSLController__MonitorAssignment_4");
					put(grammarAccess.getDSLControllerAccess().getAnalyzerAssignment_5(), "rule__DSLController__AnalyzerAssignment_5");
					put(grammarAccess.getDSLControllerAccess().getPlannerAssignment_6(), "rule__DSLController__PlannerAssignment_6");
					put(grammarAccess.getDSLControllerAccess().getExecutorAssignment_7(), "rule__DSLController__ExecutorAssignment_7");
					put(grammarAccess.getDSLControllerAccess().getKnowledgeAssignment_8(), "rule__DSLController__KnowledgeAssignment_8");
					put(grammarAccess.getDSLMonitorAccess().getNameAssignment_1(), "rule__DSLMonitor__NameAssignment_1");
					put(grammarAccess.getDSLMonitorAccess().getMonitorinterfacesAssignment_2_1(), "rule__DSLMonitor__MonitorinterfacesAssignment_2_1");
					put(grammarAccess.getDSLMonitorAccess().getMonitorinterfacesAssignment_2_2_1(), "rule__DSLMonitor__MonitorinterfacesAssignment_2_2_1");
					put(grammarAccess.getDSLAnalyzerAccess().getNameAssignment_1(), "rule__DSLAnalyzer__NameAssignment_1");
					put(grammarAccess.getDSLAnalyzerAccess().getAnlyzerinterfacesAssignment_2_1(), "rule__DSLAnalyzer__AnlyzerinterfacesAssignment_2_1");
					put(grammarAccess.getDSLAnalyzerAccess().getAnlyzerinterfacesAssignment_2_2_1(), "rule__DSLAnalyzer__AnlyzerinterfacesAssignment_2_2_1");
					put(grammarAccess.getDSLPlannerAccess().getNameAssignment_1(), "rule__DSLPlanner__NameAssignment_1");
					put(grammarAccess.getDSLPlannerAccess().getPlannerinterfacesAssignment_2_1(), "rule__DSLPlanner__PlannerinterfacesAssignment_2_1");
					put(grammarAccess.getDSLPlannerAccess().getPlannerinterfacesAssignment_2_2_1(), "rule__DSLPlanner__PlannerinterfacesAssignment_2_2_1");
					put(grammarAccess.getDSLExecutorAccess().getNameAssignment_1(), "rule__DSLExecutor__NameAssignment_1");
					put(grammarAccess.getDSLExecutorAccess().getExecutorinterfacesAssignment_2_1(), "rule__DSLExecutor__ExecutorinterfacesAssignment_2_1");
					put(grammarAccess.getDSLExecutorAccess().getExecutorinterfacesAssignment_2_2_1(), "rule__DSLExecutor__ExecutorinterfacesAssignment_2_2_1");
					put(grammarAccess.getDSLKnowledgeAccess().getNameAssignment_1(), "rule__DSLKnowledge__NameAssignment_1");
					put(grammarAccess.getDSLKnowledgeAccess().getKnowledgeinterfacesAssignment_2_1(), "rule__DSLKnowledge__KnowledgeinterfacesAssignment_2_1");
					put(grammarAccess.getDSLKnowledgeAccess().getKnowledgeinterfacesAssignment_2_2_1(), "rule__DSLKnowledge__KnowledgeinterfacesAssignment_2_2_1");
					put(grammarAccess.getDSLKnowledgeAccess().getReferenceInputAssignment_4(), "rule__DSLKnowledge__ReferenceInputAssignment_4");
					put(grammarAccess.getDSLSensorAccess().getNameAssignment_1(), "rule__DSLSensor__NameAssignment_1");
					put(grammarAccess.getDSLSensorAccess().getSensorinterfacesAssignment_2_1(), "rule__DSLSensor__SensorinterfacesAssignment_2_1");
					put(grammarAccess.getDSLSensorAccess().getSensorinterfacesAssignment_2_2_1(), "rule__DSLSensor__SensorinterfacesAssignment_2_2_1");
					put(grammarAccess.getDSLEffectorAccess().getNameAssignment_1(), "rule__DSLEffector__NameAssignment_1");
					put(grammarAccess.getDSLEffectorAccess().getEffectorinterfacesAssignment_2_1(), "rule__DSLEffector__EffectorinterfacesAssignment_2_1");
					put(grammarAccess.getDSLEffectorAccess().getEffectorinterfacesAssignment_2_2_1(), "rule__DSLEffector__EffectorinterfacesAssignment_2_2_1");
					put(grammarAccess.getDSLReferenceInputAccess().getNameAssignment_1(), "rule__DSLReferenceInput__NameAssignment_1");
					put(grammarAccess.getDSLMeasuredOutputAccess().getNameAssignment_1(), "rule__DSLMeasuredOutput__NameAssignment_1");
					put(grammarAccess.getEffectorInterfaceAccess().getNameAssignment(), "rule__EffectorInterface__NameAssignment");
					put(grammarAccess.getSensorInterfaceAccess().getNameAssignment(), "rule__SensorInterface__NameAssignment");
					put(grammarAccess.getMonitorInterfaceAccess().getNameAssignment(), "rule__MonitorInterface__NameAssignment");
					put(grammarAccess.getAnalyzerInterfaceAccess().getNameAssignment(), "rule__AnalyzerInterface__NameAssignment");
					put(grammarAccess.getPlannerInterfaceAccess().getNameAssignment(), "rule__PlannerInterface__NameAssignment");
					put(grammarAccess.getExecutorInterfaceAccess().getNameAssignment(), "rule__ExecutorInterface__NameAssignment");
					put(grammarAccess.getKnowledgeInterfaceAccess().getNameAssignment(), "rule__KnowledgeInterface__NameAssignment");
					put(grammarAccess.getControllerInterfaceAccess().getNameAssignment(), "rule__ControllerInterface__NameAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalSasDslParser typedParser = (InternalSasDslParser) parser;
			typedParser.entryRuleArchitectureDefinition();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SasDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SasDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
